# Generated by Django 4.2.2 on 2023-08-11 17:15

import APIs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_entrys', to='APIs.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=APIs.models.order_number_generator, editable=False, max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='contact',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
