# Generated by Django 4.2.2 on 2023-08-11 17:31

import APIs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0002_alter_customer_contact_alter_entry_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=APIs.models.order_number_generator, editable=False, max_length=9, unique=True),
        ),
    ]
