# Generated by Django 4.2.2 on 2023-08-11 17:47

import APIs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0003_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=APIs.models.order_number_generator, editable=False, max_length=10, unique=True),
        ),
    ]
